sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker pull microsoft/azure-cli:0.10.0
  - docker run microsoft/azure-cli:0.10.0 bash -c "azure --version;"
script:
  - if [ $TRAVIS_BRANCH = "develop" ]; then echo "DEV deploy"; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then docker ps -a; fi
