sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker pull ubuntu
  - docker run ubuntu bash -c "uname -a;"
script:
  - if [ $TRAVIS_BRANCH = "master" ]; then docker ps -a; fi
